// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw9-mMFjXDVibB2WPJwFOL64Y7cCAFgeI',
    appId: '1:41674407799:web:27b7904e39afee543ceb72',
    messagingSenderId: '41674407799',
    projectId: 'checkio-attendance',
    authDomain: 'checkio-attendance.firebaseapp.com',
    storageBucket: 'checkio-attendance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUJ6Ze_uQD0_OVq9L2TqtzFltxa8-PnHQ',
    appId: '1:41674407799:android:a6934aa0e4ac71853ceb72',
    messagingSenderId: '41674407799',
    projectId: 'checkio-attendance',
    storageBucket: 'checkio-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnNQil993dHZWovXF5KA2WPiNbHUxGskY',
    appId: '1:41674407799:ios:fb1beabd9b3d146f3ceb72',
    messagingSenderId: '41674407799',
    projectId: 'checkio-attendance',
    storageBucket: 'checkio-attendance.firebasestorage.app',
    iosBundleId: 'com.io.cicoattendance.cicoattendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnNQil993dHZWovXF5KA2WPiNbHUxGskY',
    appId: '1:41674407799:ios:fb1beabd9b3d146f3ceb72',
    messagingSenderId: '41674407799',
    projectId: 'checkio-attendance',
    storageBucket: 'checkio-attendance.firebasestorage.app',
    iosBundleId: 'com.io.cicoattendance.cicoattendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw9-mMFjXDVibB2WPJwFOL64Y7cCAFgeI',
    appId: '1:41674407799:web:4e08fdb889eceb4c3ceb72',
    messagingSenderId: '41674407799',
    projectId: 'checkio-attendance',
    authDomain: 'checkio-attendance.firebaseapp.com',
    storageBucket: 'checkio-attendance.firebasestorage.app',
  );
}
